// Sector and Subsector options for Professional Info

export const SECTORS = [
  'RMC Plant',
  'Manufacturing',
  'Service',
  'FMCG',
  'Construction',
  'Real Estate',
  'Pharma',
  'Digital Marketing',
  'Private Banking',
  'Hotels',
  'Hospitality',
  'E-Commerce',
  'Education',
  'Healthcare',
  'Beauty & Wellness',
  'Automotive Industry',
  'Transport & Fleet Services',
  'Textile Machinery',
  'Electrical Equipment',
  'Machine Tools',
  'Fertilizers',
  'Plastic & Polymers',
  'Road & Highway',
  'Cement Industry',
  'Media & Entertainment',
  'Tourism',
  'Electric Vehicle & Battery',
  'Electronics Manufacturing',
  'Logistics & Warehousing',
  'Oil & Gas Refinery',
  'Chemicals & Petrochemicals',
  'Steel & Metals',
  'Telecommunication',
  'Agriculture',
  'Insurance',
  'Textiles & Apparel',
  'Automobile',
  'Construction Equipment',
  'Tailoring',
] as const;

export type Sector = (typeof SECTORS)[number];

export const SUBSECTORS: Record<Sector, string[]> = {
  'RMC Plant': [
    'RMC Plant Operator',
    'Batching Plant Operator',
    'Production Supervisor',
    'Production In-Charge',
    'Quality Control Engineer',
    'Concrete Lab Technician',
    'Mechanical Maintenance Technician',
    'Electrical Technician',
    'Transit Mixer Driver',
    'Concrete Pump Operator',
    'Dispatch Coordinator',
    'Weighbridge Operator',
    'Storekeeper',
    'Safety Officer',
    'Plant Helper / General Assistant',
  ],
  Manufacturing: [
    'Production Operator',
    'Production Supervisor',
    'Machine Operator',
    'CNC Machine Operator',
    'Quality Control Inspector',
    'Maintenance Technician',
    'Electrical Technician',
    'Assembly Technician',
    'Store & Inventory Executive',
    'Production Helper / General Worker',
  ],
  Service: [
    'Service Executive',
    'Customer Service Executive',
    'Field Service Technician',
    'Service Supervisor',
    'Sales Executive',
    'Field Sales Executive',
    'Delivery Executive',
    'Office / Administrative Executive',
    'Housekeeping Staff',
    'Security Guard',
  ],
  FMCG: [
    'Sales Executive',
    'Territory Sales Executive',
    'Distributor Sales Representative',
    'Merchandiser',
    'Warehouse Executive',
    'Warehouse Supervisor',
    'Inventory Executive',
    'Delivery Executive',
    'Quality Control Executive',
    'Production Operator',
  ],
  Construction: [
    'Site Engineer',
    'Site Supervisor',
    'Civil Engineer',
    'Project Engineer',
    'Construction Supervisor',
    'Mason',
    'Carpenter',
    'Shuttering Carpenter',
    'Electrician',
    'Construction Helper / General Worker',
  ],
  'Real Estate': [
    'Real Estate Sales Executive',
    'Property Consultant',
    'Real Estate Agent',
    'Business Development Executive',
    'Channel Partner Executive',
    'Customer Relationship Executive (CRE)',
    'Pre-Sales Executive',
    'Site Sales Executive',
    'Property Manager',
    'Real Estate Sales Manager',
  ],
  Pharma: [
    'Medical Representative',
    'Pharmaceutical Sales Executive',
    'Production Operator',
    'Production Supervisor',
    'Quality Control (QC) Executive',
    'Quality Assurance (QA) Executive',
    'Pharma Lab Technician',
    'Warehouse Executive',
    'Pharma Packing Operator',
    'Pharmacy Assistant',
  ],
  'Digital Marketing': [
    'Digital Marketing Executive',
    'SEO Executive',
    'Social Media Executive',
    'Content Marketing Executive',
    'Performance Marketing Executive',
    'Google Ads Specialist',
    'Social Media Marketing Specialist',
    'Graphic Designer',
    'Content Writer',
    'Digital Marketing Manager',
  ],
  'Private Banking': [
    'Relationship Manager',
    'Branch Sales Executive',
    'Customer Service Executive',
    'Banking Operations Executive',
    'Loan Officer',
    'Credit Officer',
    'Sales Officer',
    'Field Collection Executive',
    'Branch Operations Manager',
    'Business Development Executive',
  ],
  Hotels: [
    'Front Office Executive',
    'Receptionist',
    'Guest Relations Executive',
    'Housekeeping Executive',
    'Food & Beverage Executive',
    'Restaurant Supervisor',
    'Chef',
    'Kitchen Helper',
    'Hotel Sales Executive',
    'Hotel Operations Manager',
  ],
  Hospitality: [
    'Front Office Executive',
    'Guest Relations Executive',
    'Reservation Executive',
    'Housekeeping Supervisor',
    'Food & Beverage Executive',
    'Restaurant Supervisor',
    'Chef',
    'Steward',
    'Hospitality Sales Executive',
    'Hospitality Operations Manager',
  ],
  'E-Commerce': [
    'E-Commerce Executive',
    'E-Commerce Operations Executive',
    'Order Processing Executive',
    'Customer Support Executive',
    'Warehouse Executive',
    'Inventory Executive',
    'Logistics Executive',
    'Catalog Executive',
    'Digital Marketing Executive',
    'E-Commerce Operations Manager',
  ],
  Education: [
    'Teacher',
    'Subject Matter Expert',
    'Academic Coordinator',
    'School Administrator',
    'Admission Counsellor',
    'Student Counsellor',
    'Education Sales Executive',
    'Content Developer',
    'Lab Assistant',
    'Academic Operations Manager',
  ],
  Healthcare: [
    'Staff Nurse',
    'Medical Assistant',
    'Hospital Receptionist',
    'Medical Representative',
    'Pharmacist',
    'Laboratory Technician',
    'Radiology Technician',
    'Patient Care Executive',
    'Hospital Administration Executive',
    'Healthcare Operations Manager',
  ],
  'Beauty & Wellness': [
    'Beautician',
    'Hair Stylist',
    'Makeup Artist',
    'Skin Therapist',
    'Nail Technician',
    'Spa Therapist',
    'Wellness Consultant',
    'Salon Receptionist',
    'Salon Supervisor',
    'Salon / Spa Manager',
  ],
  'Automotive Industry': [
    'Automotive Technician',
    'Automobile Mechanic',
    'Service Advisor',
    'Auto Electrician',
    'Diagnostic Technician',
    'Body Repair Technician',
    'Automobile Sales Executive',
    'Spare Parts Executive',
    'Workshop Supervisor',
    'Service Center Manager',
  ],
  'Transport & Fleet Services': [
    'Fleet Manager',
    'Fleet Supervisor',
    'Transport Coordinator',
    'Logistics Coordinator',
    'Heavy Vehicle Driver',
    'Light Commercial Vehicle Driver',
    'Delivery Driver',
    'Fleet Maintenance Technician',
    'Dispatch Executive',
    'Transport Operations Manager',
  ],
  'Textile Machinery': [
    'Textile Machine Operator',
    'Machine Maintenance Technician',
    'Textile Machinery Technician',
    'CNC Machine Operator',
    'Mechanical Fitter',
    'Electrical Technician',
    'Machine Assembly Technician',
    'Quality Control Inspector',
    'Maintenance Supervisor',
    'Textile Machinery Production Supervisor',
  ],
  'Electrical Equipment': [
    'Electrical Technician',
    'Electrical Machine Operator',
    'Electrical Assembly Technician',
    'Wiring Technician',
    'Electrical Maintenance Technician',
    'Quality Control Inspector',
    'Testing & Inspection Technician',
    'Production Supervisor',
    'Electrical Design Engineer',
    'Electrical Equipment Service Engineer',
  ],
  'Machine Tools': [
    'CNC Machine Operator',
    'VMC Machine Operator',
    'CNC Programmer',
    'Machine Tool Technician',
    'Mechanical Fitter',
    'Tool & Die Maker',
    'Machine Maintenance Technician',
    'Quality Control Inspector',
    'Production Supervisor',
    'Machine Tools Service Engineer',
  ],
  Fertilizers: [
    'Production Operator',
    'Chemical Plant Operator',
    'Production Supervisor',
    'Process Technician',
    'Quality Control Technician',
    'Laboratory Technician',
    'Mechanical Maintenance Technician',
    'Electrical Maintenance Technician',
    'Warehouse & Inventory Executive',
    'Plant Operations Manager',
  ],
  'Plastic & Polymers': [
    'Plastic Machine Operator',
    'Injection Molding Operator',
    'Extrusion Machine Operator',
    'Blow Molding Operator',
    'Mold Maintenance Technician',
    'Production Supervisor',
    'Quality Control Inspector',
    'Polymer Processing Technician',
    'Mechanical Maintenance Technician',
    'Plastic Manufacturing Manager',
  ],
  'Road & Highway': [
    'Site Engineer',
    'Civil Engineer',
    'Site Supervisor',
    'Road Construction Supervisor',
    'Highway Project Engineer',
    'Surveyor',
    'Heavy Equipment Operator',
    'Excavator Operator',
    'Road Roller Operator',
    'Construction Helper',
  ],
  'Cement Industry': [
    'Production Operator',
    'Kiln Operator',
    'Cement Mill Operator',
    'Quality Control Technician',
    'Laboratory Technician',
    'Mechanical Maintenance Technician',
    'Electrical Maintenance Technician',
    'Packing Machine Operator',
    'Dispatch & Logistics Executive',
    'Plant Operations Manager',
  ],
  'Media & Entertainment': [
    'Content Creator',
    'Video Editor',
    'Graphic Designer',
    'Social Media Executive',
    'Camera Operator',
    'Photographer',
    'Sound Technician',
    'Production Assistant',
    'Production Coordinator',
    'Media & Entertainment Manager',
  ],
  Tourism: [
    'Travel Consultant',
    'Travel Agent',
    'Tour Coordinator',
    'Tour Guide',
    'Travel Executive',
    'Reservation Executive',
    'Ticketing Executive',
    'Travel Operations Executive',
    'Tourism Sales Executive',
    'Travel Operations Manager',
  ],
  'Electric Vehicle & Battery': [
    'EV Technician',
    'EV Service Technician',
    'Battery Technician',
    'Battery Assembly Operator',
    'EV Production Operator',
    'Electrical Technician',
    'Battery Testing Technician',
    'EV Quality Control Technician',
    'EV Maintenance Supervisor',
    'EV Service & Operations Manager',
  ],
  'Electronics Manufacturing': [
    'Electronics Production Operator',
    'PCB Assembly Technician',
    'SMT Machine Operator',
    'Electronics Assembly Technician',
    'Testing & Inspection Technician',
    'Electronics Repair Technician',
    'Quality Control Inspector',
    'Electronics Maintenance Technician',
    'Production Supervisor',
    'Electronics Manufacturing Engineer',
  ],
  'Logistics & Warehousing': [
    'Warehouse Associate',
    'Warehouse Supervisor',
    'Logistics Executive',
    'Logistics Coordinator',
    'Inventory Executive',
    'Storekeeper',
    'Dispatch Executive',
    'Picker & Packer',
    'Loading & Unloading Executive',
    'Logistics Operations Manager',
  ],
  'Oil & Gas Refinery': [
    'Refinery Plant Operator',
    'Process Operator',
    'Production Supervisor',
    'Process Technician',
    'Mechanical Maintenance Technician',
    'Electrical Technician',
    'Instrumentation Technician',
    'Quality Control Technician',
    'Safety Officer',
    'Refinery Operations Manager',
  ],
  'Chemicals & Petrochemicals': [
    'Chemical Plant Operator',
    'Process Operator',
    'Production Supervisor',
    'Process Technician',
    'Chemical Laboratory Technician',
    'Quality Control Technician',
    'Mechanical Maintenance Technician',
    'Electrical Technician',
    'Instrumentation Technician',
    'Plant Operations Manager',
  ],
  'Steel & Metals': [
    'Steel Plant Operator',
    'Furnace Operator',
    'Rolling Mill Operator',
    'Production Supervisor',
    'Mechanical Maintenance Technician',
    'Electrical Technician',
    'Metallurgy Technician',
    'Quality Control Inspector',
    'Crane Operator',
    'Plant Operations Manager',
  ],
  Telecommunication: [
    'Telecom Technician',
    'Network Technician',
    'Fiber Optic Technician',
    'Telecom Installation Technician',
    'Tower Technician',
    'Field Service Technician',
    'Network Operations Executive',
    'Customer Support Executive',
    'Telecom Project Supervisor',
    'Telecom Operations Manager',
  ],
  Agriculture: [
    'Farm Supervisor',
    'Agriculture Field Officer',
    'Farm Worker',
    'Agricultural Equipment Operator',
    'Tractor Operator',
    'Irrigation Technician',
    'Agricultural Technician',
    'Nursery & Horticulture Worker',
    'Agricultural Sales Executive',
    'Agriculture Operations Manager',
  ],
  Insurance: [
    'Insurance Advisor',
    'Insurance Sales Executive',
    'Relationship Manager',
    'Customer Service Executive',
    'Insurance Agent',
    'Claims Executive',
    'Underwriting Executive',
    'Policy Servicing Executive',
    'Field Collection Executive',
    'Insurance Branch Manager',
  ],
  'Textiles & Apparel': [
    'Textile Machine Operator',
    'Garment Production Operator',
    'Sewing Machine Operator',
    'Cutting Machine Operator',
    'Tailor',
    'Quality Control Inspector',
    'Production Supervisor',
    'Embroidery Operator',
    'Packing & Finishing Executive',
    'Textile & Garment Production Manager',
  ],
  Automobile: [
    'Automobile Technician',
    'Automobile Mechanic',
    'Service Advisor',
    'Auto Electrician',
    'Diagnostic Technician',
    'Body Repair Technician',
    'Automobile Sales Executive',
    'Spare Parts Executive',
    'Workshop Supervisor',
    'Automobile Service Manager',
  ],
  'Construction Equipment': [
    'Heavy Equipment Operator',
    'Excavator Operator',
    'JCB Operator',
    'Crane Operator',
    'Forklift Operator',
    'Equipment Maintenance Technician',
    'Diesel Mechanic',
    'Equipment Service Technician',
    'Equipment Service Supervisor',
    'Construction Equipment Operations Manager',
  ],
  Tailoring: [
    'Tailor',
    'Master Tailor',
    'Sewing Machine Operator',
    'Garment Stitching Operator',
    'Cutting Master',
    'Pattern Maker',
    'Embroidery Operator',
    'Alteration Specialist',
    'Quality Control Inspector',
    'Tailoring Supervisor',
  ],
};

export function getSectorsList(): string[] {
  return [...SECTORS];
}

export function getSubsectorsForSector(sector: string): string[] {
  return SUBSECTORS[sector as Sector] || [];
}
